version: '3'

tasks:
  gen:
    cmds:
      - |
        protoc --proto_path=. \
        --go_out=. --go_opt=paths=source_relative  \
        --go-grpc_out=require_unimplemented_servers=false:. --go-grpc_opt=paths=source_relative \
        data.proto        
